name: demo

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    strategy:
      matrix:
        os: [ubuntu-22.04,ubuntu-20.04]
        version: [10,12,14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}    